services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - "ollama_data:/root/.ollama"

  app:
   build: .
   container_name: ai-devops-app
   ports:
      - "8000:8000"
   depends_on:
      - "ollama"
volumes:
  ollama_data:  



    
